#!/usr/bin/env perl
use 5.14.2;
use Term::ANSIColor ':constants';
say BLACK, "BLACK", RESET, "\t", BRIGHT_BLACK, "BRIGHT", RESET;
say RED, "RED", RESET, "\t", BRIGHT_RED, "BRIGHT", RESET;
say GREEN, "GREEN", RESET, "\t", BRIGHT_GREEN, "BRIGHT", RESET;
say YELLOW, "YELLOW", RESET, "\t", BRIGHT_YELLOW, "BRIGHT", RESET;
say BLUE, "BLUE", RESET, "\t", BRIGHT_BLUE, "BRIGHT", RESET;
say MAGENTA, "MAGENTA", RESET, "\t", BRIGHT_MAGENTA, "BRIGHT", RESET;
say CYAN, "CYAN", RESET, "\t", BRIGHT_CYAN, "BRIGHT", RESET;
say WHITE, "WHITE", RESET, "\t", BRIGHT_WHITE, "BRIGHT", RESET;
say BOLD, "BOLD", RESET, "\t", UNDERLINE, "UNDERLINE", RESET;
